version: '3.1'

services:
  api:
    build: .
    ports:
      - 3333:3333
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - HOST=0.0.0.0
      - LOG_LEVEL=${LOG_LEVEL}
      - APP_KEY=${APP_KEY}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: be-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: be_db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p1234"]
      interval: 10s
      timeout: 5s
      retries: 3
